# Generated by Django 6.0.5 on 2026-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_rsvp_approval',
            field=models.BooleanField(default=False, help_text='If checked, you must manually approve each RSVP before the person is confirmed. Leave unchecked to approve everyone instantly.'),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_redirect_url',
            field=models.URLField(blank=True, help_text='Optional: send attendees to this link right after their RSVP is approved (e.g. a WhatsApp group or payment page). Leave blank to keep them on the event page.', null=True),
        ),
    ]
