# Generated by Django 6.0.5 on 2026-10-01 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_require_rsvp_approval_event_rsvp_redirect_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Event',
                'verbose_name_plural': 'Saved Events',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
