# Generated by Django 4.2.7 on 2026-07-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_event', 'New event from someone you follow'), ('rsvp_request', 'Someone requested to join your event'), ('rsvp_approved', 'Your request to join was approved')], default='new_event', max_length=30),
        ),
    ]
